// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.WordLexiconAnalyzer
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("word")]
        public string Word { get; set; }

        [JsonProperty("isAlphagram")]
        public bool? IsAlphagram { get; set; }

        [JsonProperty("sortedForm")]
        public string SortedForm { get; set; }

        [JsonProperty("isPalindrome")]
        public bool? IsPalindrome { get; set; }

        [JsonProperty("hasAnagram")]
        public bool? HasAnagram { get; set; }

        [JsonProperty("isIsogram")]
        public bool? IsIsogram { get; set; }

        [JsonProperty("isPangramCandidate")]
        public bool? IsPangramCandidate { get; set; }

        [JsonProperty("isScrabbleValid")]
        public bool? IsScrabbleValid { get; set; }

        [JsonProperty("canBePalindromeAnagram")]
        public bool? CanBePalindromeAnagram { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
